"""Measure how long the PLDI type checker takes on LLM-generated TypeScript.

No GPU and no model. It reuses programs the LLM already wrote in the paper's
experiments, feeds each one to the checker, and times it.

    python3 profile_advance.py          # 10 programs
    python3 profile_advance.py 60       # 60 programs

Needs Python 3.11 and: frozenlist regex termcolor frozendict
"""

import json
import os
import statistics
import sys
import time

REPO = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "..", "type-constrained-code-generation"
)
sys.path.insert(0, REPO)

RESULTS = os.path.join(
    REPO,
    "experiments/main/results_paper",
    "mbpp_google_gemma-2-2b-it_s=0_t=1_synth_c.jsonl",
)

# Saved records store the LLM's program with the benchmark's own correctness tests
# glued onto the end. Those tests were never generated by the LLM and the checker
# never saw them during generation, so we cut them off here.
TEST_MARKER = "declare var require"

# The checker was run with this as the end-of-code marker during generation.
END_MARKER = "```"

from typesafe_llm.parser.parser_ts import (  # noqa: E402
    custom_end_initial_state,
    incremental_ts_parse,
)


def load_programs(limit):
    """Return [(instance_id, program_text)], LLM-written text only."""
    programs = []
    with open(RESULTS) as handle:
        for line in handle:
            try:
                record = json.loads(line)
            except ValueError:
                continue
            if record.get("crashed") not in (None, "None"):
                continue  # generation errored
            if record.get("time_taken", 0) >= 295:
                continue  # hit the 300s timeout
            text = record.get("compilable") or ""
            marker = text.find(TEST_MARKER)
            if marker >= 0:
                text = text[:marker]  # drop the benchmark's tests
            text = text.rstrip()
            if text:
                programs.append((record["instance_id"], text))
    programs.sort(key=lambda p: p[0])
    return programs[:limit]


def check_one(text):
    """Run the checker over one program. Returns (seconds, chars_read, live_states)."""
    state = custom_end_initial_state(END_MARKER, {})
    start = time.perf_counter()
    result = incremental_ts_parse(state, text)
    seconds = time.perf_counter() - start
    return seconds, len(result.parsed_code), len(result)


def main():
    limit = int(sys.argv[1]) if len(sys.argv) > 1 else 10
    programs = load_programs(limit)
    print(f"{len(programs)} programs from {os.path.basename(RESULTS)}\n")
    print(f"{'program':<44}{'chars':>7}{'seconds':>10}{'ms/char':>10}{'states':>8}  note")

    rows = []
    for name, text in programs:
        seconds, chars_read, states = check_one(text)
        ms_per_char = seconds * 1000.0 / chars_read if chars_read else float("nan")
        # The checker should read the whole program. If it stops early, it rejected
        # something, and the timing only covers the part it read.
        note = "" if chars_read == len(text) else f"STOPPED EARLY at {chars_read}/{len(text)}"
        rows.append((name, chars_read, seconds, ms_per_char, states, note))
        print(
            f"{name[:44]:<44}{chars_read:>7}{seconds:>10.2f}{ms_per_char:>10.2f}"
            f"{states:>8}  {note}",
            flush=True,
        )

    total_seconds = sum(r[2] for r in rows)
    total_chars = sum(r[1] for r in rows)
    per_char = [r[3] for r in rows if r[3] == r[3]]
    slowest = max(rows, key=lambda r: r[3])

    print(f"\ntotal: {total_chars} chars in {total_seconds:.2f}s")
    print(f"typical program  : {statistics.median(per_char):.2f} ms/char (median)")
    print(f"overall average  : {total_seconds * 1000.0 / total_chars:.2f} ms/char")
    print(f"slowest program  : {slowest[0]} at {slowest[3]:.2f} ms/char, {slowest[4]} states")
    print(f"fully read       : {sum(1 for r in rows if not r[5])}/{len(rows)}")


if __name__ == "__main__":
    main()
